# Generated by Django 4.2.4 on 2023-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='catalog.category'),
        ),
    ]
