# Generated by Django 4.2.6 on 2023-10-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_option_optiongroup_productclass_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='options',
        ),
        migrations.AddField(
            model_name='productclass',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.option'),
        ),
    ]
